remove tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -273,76 +273,76 @@ jobs:
               -S ci/if_feat_check.vim -c quit
           fi
 
-      - name: Test
-        if: matrix.architecture != 'arm64'
-        timeout-minutes: 25
-        run: |
-          make ${SHADOWOPT} ${TEST}
-
-      - name: Check feature flags
-        if: (!contains(matrix.extra, 'unittests') && matrix.features == 'huge')
-        run: |
-          # Check that optional or dynamic features are configured and working
-          FEATURES=( \
-            gettext \
-            sodium \
-            sound \
-            perl \
-            python3 \
-            lua \
-            ruby \
-            tcl \
-          )
-          for feat in "${FEATURES[@]}"; do
-            echo "Checking has('${feat}')"
-            "${SRCDIR}"/vim -u NONE -i NONE -es -c "if has('${feat}') | quit | else | cquit | endif"
-          done
-
-
-      # `sg audio` does not work on arm64 runner due to permission ('Incorrect password' error).
-      - name: Test on arm64
-        if: matrix.architecture == 'arm64'
-        timeout-minutes: 25
-        run: |
-          make ${SHADOWOPT} ${TEST}
-
-      - if: ${{ !cancelled() }}
-        uses: ./.github/actions/test_artifacts
-
-      - name: Vim tags
-        if: contains(matrix.extra, 'vimtags')
-        run: |
-          # This will exit with an error code if the generated vim tags differs from source.
-          (
-            cd runtime/doc
-            git diff --exit-code -- tags
-            make html; rm *.html tags.ref;
-            test -f errors.log && exit 3;
-            true
-          )
-
-      - name: Generate gcov files
-        if: matrix.coverage
-        run: |
-          cd "${SRCDIR}"
-          find . -type f -name '*.gcno' -exec gcov -pb {} + || true
-
-      - name: Codecov
-        timeout-minutes: 20
-        if: matrix.coverage
-        uses: codecov/codecov-action@v5
-        with:
-          flags: linux,${{ matrix.features }}-${{ matrix.compiler }}-${{ join(matrix.extra, '-') }}
-          token: ${{ secrets.CODECOV_TOKEN }}
-
-      - name: ASan logs
-        if: contains(matrix.extra, 'asan') && !cancelled()
-        run: |
-          for f in $(grep -lR '#[[:digit:]]* *0x[[:xdigit:]]*' "${LOG_DIR}"); do
-            echo "$f"
-            asan_symbolize -l "$f"
-            false # in order to fail a job
-          done
+#      - name: Test
+#        if: matrix.architecture != 'arm64'
+#        timeout-minutes: 25
+#        run: |
+#          make ${SHADOWOPT} ${TEST}
+#
+#      - name: Check feature flags
+#        if: (!contains(matrix.extra, 'unittests') && matrix.features == 'huge')
+#        run: |
+#          # Check that optional or dynamic features are configured and working
+#          FEATURES=( \
+#            gettext \
+#            sodium \
+#            sound \
+#            perl \
+#            python3 \
+#            lua \
+#            ruby \
+#            tcl \
+#          )
+#          for feat in "${FEATURES[@]}"; do
+#            echo "Checking has('${feat}')"
+#            "${SRCDIR}"/vim -u NONE -i NONE -es -c "if has('${feat}') | quit | else | cquit | endif"
+#          done
+#
+#
+#      # `sg audio` does not work on arm64 runner due to permission ('Incorrect password' error).
+#      - name: Test on arm64
+#        if: matrix.architecture == 'arm64'
+#        timeout-minutes: 25
+#        run: |
+#          make ${SHADOWOPT} ${TEST}
+#
+#      - if: ${{ !cancelled() }}
+#        uses: ./.github/actions/test_artifacts
+#
+#      - name: Vim tags
+#        if: contains(matrix.extra, 'vimtags')
+#        run: |
+#          # This will exit with an error code if the generated vim tags differs from source.
+#          (
+#            cd runtime/doc
+#            git diff --exit-code -- tags
+#            make html; rm *.html tags.ref;
+#            test -f errors.log && exit 3;
+#            true
+#          )
+#
+#      - name: Generate gcov files
+#        if: matrix.coverage
+#        run: |
+#          cd "${SRCDIR}"
+#          find . -type f -name '*.gcno' -exec gcov -pb {} + || true
+#
+#      - name: Codecov
+#        timeout-minutes: 20
+#        if: matrix.coverage
+#        uses: codecov/codecov-action@v5
+#        with:
+#          flags: linux,${{ matrix.features }}-${{ matrix.compiler }}-${{ join(matrix.extra, '-') }}
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#
+#      - name: ASan logs
+#        if: contains(matrix.extra, 'asan') && !cancelled()
+#        run: |
+#          for f in $(grep -lR '#[[:digit:]]* *0x[[:xdigit:]]*' "${LOG_DIR}"); do
+#            echo "$f"
+#            asan_symbolize -l "$f"
+#            false # in order to fail a job
+#          done
 
   macos:
     runs-on: ${{ matrix.runner }}
@@ -423,36 +423,36 @@ jobs:
               -c "let g:required=['sound', 'perl', 'python3', 'lua', 'ruby', 'tcl']" \
               -S ci/if_feat_check.vim -c quit
           fi
-
-      - name: Check feature flags
-        if: (matrix.features == 'huge')
-        run: |
-          # Check that optional or dynamic features are configured and working
-          FEATURES=( \
-            sound \
-            perl \
-            python3 \
-            lua \
-            ruby \
-            tcl \
-          )
-          for feat in "${FEATURES[@]}"; do
-            echo "Checking has('${feat}')"
-            "${SRCDIR}"/vim -u NONE -i NONE -es -c "if has('${feat}') | quit | else | cquit | endif"
-          done
-
-      - name: Install packages for testing
-        run: |
-          # Apple diff is broken. Use GNU diff instead. See #14032.
-          brew install diffutils
-
-      - name: Test
-        timeout-minutes: 25
-        run: |
-          make ${TEST}
-
-      - if: ${{ !cancelled() }}
-        uses: ./.github/actions/test_artifacts
+#
+#      - name: Check feature flags
+#        if: (matrix.features == 'huge')
+#        run: |
+#          # Check that optional or dynamic features are configured and working
+#          FEATURES=( \
+#            sound \
+#            perl \
+#            python3 \
+#            lua \
+#            ruby \
+#            tcl \
+#          )
+#          for feat in "${FEATURES[@]}"; do
+#            echo "Checking has('${feat}')"
+#            "${SRCDIR}"/vim -u NONE -i NONE -es -c "if has('${feat}') | quit | else | cquit | endif"
+#          done
+#
+#      - name: Install packages for testing
+#        run: |
+#          # Apple diff is broken. Use GNU diff instead. See #14032.
+#          brew install diffutils
+#
+#      - name: Test
+#        timeout-minutes: 25
+#        run: |
+#          make ${TEST}
+#
+#      - if: ${{ !cancelled() }}
+#        uses: ./.github/actions/test_artifacts
 
   windows:
     runs-on: windows-2022
@@ -731,67 +731,67 @@ jobs:
       #    name: vim${{ matrix.bits }}-${{ matrix.toolchain }}
       #    path: ./artifacts
 
-      - name: Install packages for testing
-        shell: bash
-        run: |
-          if ${{ matrix.features != 'TINY' }}; then
-            if ${{ matrix.arch == 'x64' }}; then
-              choco install netbeans --no-progress
-            else
-              exit 0
-            fi
-          fi
-
-      - name: Test and show the result of testing gVim
-        if: matrix.GUI == 'yes' || matrix.VIMDLL == 'yes'
-        shell: cmd
-        timeout-minutes: 15
-        run: |
-          PATH %LUA_DIR%;C:\msys64\%MSYSTEM%\bin;%PATH%;%PYTHON3_DIR%;%SODIUM_LIB%
-          call "%VCVARSALL%" %VCARCH%
-
-          echo %COL_GREEN%Test gVim:%COL_RESET%
-          cd src\testdir
-          if "${{ matrix.GUI }}"=="yes" (
-            nmake -nologo -f Make_mvc.mak VIMPROG=..\gvim || exit 1
-          ) else (
-            @rem Run only tiny tests.
-            nmake -nologo -f Make_mvc.mak tiny VIMPROG=..\gvim  || exit 1
-          )
-
-      - name: Test and show the result of testing Vim
-        if: matrix.GUI == 'no' || matrix.VIMDLL == 'yes'
-        shell: cmd
-        timeout-minutes: 15
-        run: |
-          PATH %LUA_DIR%;C:\msys64\%MSYSTEM%\bin;%PATH%;%PYTHON3_DIR%;%SODIUM_LIB%
-          call "%VCVARSALL%" %VCARCH%
-
-          echo %COL_GREEN%Test Vim:%COL_RESET%
-          cd src\testdir
-          nmake -nologo -f Make_mvc.mak clean
-          if "${{ matrix.GUI }}"=="no" (
-            nmake -nologo -f Make_mvc.mak VIMPROG=..\vim || exit 1
-          ) else (
-            @rem Run only tiny tests.
-            nmake -nologo -f Make_mvc.mak tiny VIMPROG=..\vim  || exit 1
-          )
-
-      - if: ${{ !cancelled() }}
-        uses: ./.github/actions/test_artifacts
-
-      - name: Generate gcov files
-        if: matrix.coverage
-        shell: msys2 {0}
-        run: |
-          cd src
-          find . -type f -name '*.gcno' -exec gcov -pb {} + || true
-
-      - name: Codecov
-        timeout-minutes: 20
-        if: matrix.coverage
-        uses: codecov/codecov-action@v5
-        with:
-          directory: src
-          flags: windows,${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.features }}
-          token: ${{ secrets.CODECOV_TOKEN }}
+#      - name: Install packages for testing
+#        shell: bash
+#        run: |
+#          if ${{ matrix.features != 'TINY' }}; then
+#            if ${{ matrix.arch == 'x64' }}; then
+#              choco install netbeans --no-progress
+#            else
+#              exit 0
+#            fi
+#          fi
+#
+#      - name: Test and show the result of testing gVim
+#        if: matrix.GUI == 'yes' || matrix.VIMDLL == 'yes'
+#        shell: cmd
+#        timeout-minutes: 15
+#        run: |
+#          PATH %LUA_DIR%;C:\msys64\%MSYSTEM%\bin;%PATH%;%PYTHON3_DIR%;%SODIUM_LIB%
+#          call "%VCVARSALL%" %VCARCH%
+#
+#          echo %COL_GREEN%Test gVim:%COL_RESET%
+#          cd src\testdir
+#          if "${{ matrix.GUI }}"=="yes" (
+#            nmake -nologo -f Make_mvc.mak VIMPROG=..\gvim || exit 1
+#          ) else (
+#            @rem Run only tiny tests.
+#            nmake -nologo -f Make_mvc.mak tiny VIMPROG=..\gvim  || exit 1
+#          )
+#
+#      - name: Test and show the result of testing Vim
+#        if: matrix.GUI == 'no' || matrix.VIMDLL == 'yes'
+#        shell: cmd
+#        timeout-minutes: 15
+#        run: |
+#          PATH %LUA_DIR%;C:\msys64\%MSYSTEM%\bin;%PATH%;%PYTHON3_DIR%;%SODIUM_LIB%
+#          call "%VCVARSALL%" %VCARCH%
+#
+#          echo %COL_GREEN%Test Vim:%COL_RESET%
+#          cd src\testdir
+#          nmake -nologo -f Make_mvc.mak clean
+#          if "${{ matrix.GUI }}"=="no" (
+#            nmake -nologo -f Make_mvc.mak VIMPROG=..\vim || exit 1
+#          ) else (
+#            @rem Run only tiny tests.
+#            nmake -nologo -f Make_mvc.mak tiny VIMPROG=..\vim  || exit 1
+#          )
+#
+#      - if: ${{ !cancelled() }}
+#        uses: ./.github/actions/test_artifacts
+#
+#      - name: Generate gcov files
+#        if: matrix.coverage
+#        shell: msys2 {0}
+#        run: |
+#          cd src
+#          find . -type f -name '*.gcno' -exec gcov -pb {} + || true
+#
+#      - name: Codecov
+#        timeout-minutes: 20
+#        if: matrix.coverage
+#        uses: codecov/codecov-action@v5
+#        with:
+#          directory: src
+#          flags: windows,${{ matrix.toolchain }}-${{ matrix.arch }}-${{ matrix.features }}
+#          token: ${{ secrets.CODECOV_TOKEN }}
